### PR TITLE
fix cidr calculations

### PR DESCRIPTION
**Pull request by JaredGordon**
Hello!

We're having issues with CIDR errors when we try to create a /20 VPC. If we set the CIDR prefix to /20 we get errors such as this:

```
* module.infra.data.template_file.infrastructure_subnet_gateways[2]: cidrhost: prefix of 32 does not accommodate a host numbered 1 in:

${cidrhost(element(aws_subnet.infrastructure_subnets.*.cidr_block, count.index), 1)}
```

This PR fixes this, plus it consolidates the cidr subnet calculations into a module so they are easier to understand and maintain.

### CODE REVIEW

**Comment by nmahoney-pivotal** [comment]
Hey @JaredGordon. I'm reviewing this right now. I have a quick question about your latest commit (["pull down latest provider versions"](https://github.com/pivotal-cf/terraforming-aws/pull/108/commits/80c1b015a2a0aeef6a1e4f6f3de758628a81c76d)).

What is your thinking behind this change? The [`~>` syntax](https://www.terraform.io/docs/configuration/providers.html#gt-1-2) that you replaced means at least that value (`1.60`) but less than the next major (`2.0.0`). So your commit message says to pull latest version, but the effect of the change is just to allow versions less than `1.60`. If that wasn't your intention, could you remove that commit?

**Comment by JaredGordon** [comment]
hey folks, am closing this and am going to re-submit an almost identical one that does not have merge conflicts...

**Comment by JaredGordon** [comment]
Thanks Nick, yes, that was not intentional, I removed and resubmitted a
fixed up PR. Sorry about that...

**Comment by nmahoney-pivotal** [comment]
No worries!

**Pull request closed without merging**
