### PR TITLE
Adds option to disable Route 53, required for Gov Cloud.

### PR DESCRIPTION
**Pull request by voor**
There's no Route 53 service in Gov Cloud, so interacting with those resources would cause errors.

Also adds the nat AMI ID from GovCloud west.

Based on the work from @goehringc here https://github.com/goehringc/terraforming-aws/tree/aws_govcloud_support but updated to reflect changes in folder structure.

### CODE REVIEW

**Comment by voor** [comment]
This was merged effectively with https://github.com/pivotal-cf/terraforming-aws/commit/323eef94a05ad76b565ab2898260a6421ec89870

**Comment by cdutra** [comment]
@voor Do you want to close this? This hasn't been merged yet.

**Comment by cdutra** [comment]
@voor We could infer if user is using Gov Cloud from the [region variable](). Reference: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Concepts.RegionsAndAvailabilityZones.html

**Comment by cdutra** [comment]
Merged in master. Thanks fo the PR!

**Pull request closed without merging**
